import { 
  IoGrid, 
  IoSettings, 
  IoSettingsOutline, 
  IoPerson, 
  IoPersonOutline, 
  IoPeople, 
  IoPeopleOutline, 
  IoFlag, 
  IoFlagOutline, 
  IoLink, 
  IoLinkOutline, 
  IoPulse, 
  IoHeart, 
  IoCheckmarkCircle, 
  IoLinkSharp, 
  IoBusiness, 
  IoFlash, 
  IoOptions, 
  IoServer, 
  IoChatbubble, 
  IoDocument, 
  IoMail, 
  IoFolder, 
  IoKey, 
  IoMenu, 
  IoPersonCircle, 
  IoCloudUpload, 
  IoCloudDownload, 
  IoCash, 
  IoLocate, 
  IoCalculator, 
  IoMap, 
  IoMegaphone, 
  IoBan, 
  IoBriefcase, 
  IoCube, 
  IoGift, 
  IoSpeedometer, 
  IoSpeedometerOutline, 
  IoWallet, 
  IoWalletOutline, 
  IoDocumentText, 
  IoDocumentTextOutline, 
} from "react-icons/io5"; 
import type { NavItem } from "@/shared/custom-ui/sidebar/types"; 
 
export const dashboardNavigationItems: NavItem[] = [ 
  // Main Tab Order: Dashboard, Customers, Manage Leads, Profile Management, Call Center, Configuration, Transaction, Reporting, Quick Link 
  { 
    id: "dashboard", 
    label: "Dashboard", 
    icon: IoSpeedometer, 
    iconOutline: IoSpeedometerOutline, 
    subMenus: [ 
      { 
        id: "dashboard-tab", 
        label: "Dashboard", 
        path: "/dashboard", 
        icon: IoGrid, 
 
      }, 
      { 
        id: "activity", 
        label: "Activity", 
        path: "/dashboard/activity-tab", 
        icon: IoPulse, 
      }, 
      { 
        id: "vitals", 
        label: "Vitals", 
        path: "/dashboard/vitals-tab", 
        icon: IoHeart, 
      }, 
    ], 
  }, 
  
  { 
    id: "customers", 
    label: "Customers", 
    icon: IoPeople, 
    iconOutline: IoPeopleOutline, 
    path: "/customers/incomplete", 
  },
  {
    id: "users",
    label: "Users Management",
    icon: IoPerson,
    iconOutline: IoPersonOutline,
    path: "/dashboard/users",
  }, 
    { 
    id: "transaction", 
    label: "Transaction", 
    icon: IoWallet, 
    iconOutline: IoWalletOutline, 
    subMenus: [ 
      // Transaction Order: Approve Loans, Pending Credits, Pending Debits, Create ACH File, Return File Processing 
      { 
        id: "approve", 
        label: "Approve Loans", 
        path: "/dashboard/transaction/approve", 
        icon: IoCheckmarkCircle, 
        // badge: "New", 
      }, 
      { 
        id: "credits", 
        label: "Pending Credits", 
        path: "/dashboard/transaction/credits", 
        icon: IoCash, 
      }, 
      { 
        id: "debits", 
        label: "Pending Debits", 
        path: "/dashboard/transaction/debits", 
        icon: IoCash, 
      }, 
      { 
        id: "create-ach", 
        label: "Create ACH File", 
        path: "/dashboard/transaction/create-ach", 
        icon: IoCloudDownload, 
      }, 
      { 
        id: "return-file", 
        label: "Return File Processing", 
        path: "/dashboard/transaction/return-file", 
        icon: IoCloudUpload, 
      }, 
    ], 
  }, 
  { 
    id: "manage-leads", 
    label: "Manage Leads", 
    icon: IoFlag, 
    iconOutline: IoFlagOutline, 
    subMenus: [ 
      // Manage Leads Order: Portfolio, Product, Campaign, Campaign Config, Rebate, Portfolio Mapping, Blacklist Management, Lead, Scoring Cost 
      { 
        id: "portfolio", 
        label: "Portfolio", 
        path: "/dashboard/leads/portfolio", 
        icon: IoBriefcase, 
      }, 
      { 
        id: "product", 
        label: "Product", 
        path: "/dashboard/leads/product", 
        icon: IoCube, 
      }, 
      { 
        id: "campaign", 
        label: "Campaign", 
        path: "/dashboard/dummy", 
        icon: IoMegaphone, 
      }, 
    {
  id: "campaign-config",
  label: "Campaign Config",
  path: "/dashboard/campaign-config",
  icon: IoSettings,
},
      { 
        id: "rebate", 
        label: "Rebate", 
        path: "/dashboard/leads/rebate", 
        icon: IoGift, 
      }, 
      { 
        id: "mapping", 
        label: "Portfolio Mapping", 
        path: "/dashboard/leads/mapping", 
        icon: IoMap, 
      }, 
      { 
        id: "blacklist", 
        label: "Blacklist Management", 
        path: "/dashboard/leads/blacklist", 
        icon: IoBan, 
      }, 
      { 
        id: "lead", 
        label: "Lead", 
        path: "/dashboard/leads/lead", 
        icon: IoLocate, 
        badge: 45, 
      }, 
      { 
        id: "scoring", 
        label: "Scoring Cost", 
        path: "/dashboard/leads/scoring", 
        icon: IoCalculator, 
      }, 
    ], 
  }, 
  { 
    id: "profile", 
    label: "Profile Management", 
    icon: IoPerson, 
    iconOutline: IoPersonOutline, 
    subMenus: [ 
      // Profile Management Order: Manage User Profile, Manage User Menu, Change Password 
      { 
        id: "user-profile", 
        label: "Manage User Profile", 
        path: "/dashboard/profile/user-profile", 
        icon: IoPersonCircle, 
      }, 
      { 
        id: "user-menu", 
        label: "Manage User Menu", 
        path: "/dashboard/profile/user-menu", 
        icon: IoMenu, 
      }, 
      { 
        id: "password", 
        label: "Change Password", 
        path: "/dashboard/profile/password", 
        icon: IoKey, 
      }, 
    ], 
  }, 
  // Call Center - Commented out for now, will be enabled later 
  // { 
  //   id: "call-center", 
  //   label: "Call Center", 
  //   icon: IoCall, 
  //   iconOutline: IoCallOutline, 
  //   subMenus: [ 
  //     {  
  //       id: "verification",  
  //       label: "Verification Process",  
  //       path: "/dashboard/call-center/verification", 
  //       icon: IoCall, 
  //     }, 
  //     {  
  //       id: "config",  
  //       label: "Configure Call Queue",  
  //       path: "/dashboard/call-center/config", 
  //       icon: IoSettings, 
  //     }, 
  //     {  
  //       id: "workspace",  
  //       label: "Create WorkSpace",  
  //       path: "/dashboard/call-center/workspace", 
  //       icon: IoSettings, 
  //     }, 
  //     {  
  //       id: "mapping",  
  //       label: "WorkSpace Mapping",  
  //       path: "/dashboard/call-center/mapping", 
  //       icon: IoSettings, 
  //     }, 
  //   ], 
  // }, 
  { 
    id: "configuration", 
    label: "Configuration", 
    icon: IoSettings, 
    iconOutline: IoSettingsOutline, 
    subMenus: [ 
      // Configuration Order: Documents, Email, SMS/PUSH, ACH File, ACH Provider, Bureau, Auto Origination, Underwriting, General, Quick Links 
      { 
        id: "documents", 
        label: "Documents", 
        path: "/dashboard/config/documents", 
        icon: IoFolder, 
      }, 
      { 
        id: "email", 
        label: "Email", 
        path: "/dashboard/config/email", 
        icon: IoMail, 
      }, 
      { 
        id: "sms", 
        label: "SMS", 
        path: "/dashboard/config/sms", 
        icon: IoChatbubble, 
      }, 
      { 
        id: "ach-file", 
        label: "ACH File", 
        path: "/dashboard/config/ach-file", 
        icon: IoDocument, 
      }, 
      { 
        id: "ach-provider", 
        label: "ACH Provider", 
        path: "/dashboard/config/ach-provider", 
        icon: IoBusiness, 
      }, 
      { 
        id: "bureau", 
        label: "Bureau", 
        path: "/dashboard/config/bureau", 
        icon: IoServer, 
      }, 
      { 
        id: "auto-origination", 
        label: "Auto Origination", 
        path: "/dashboard/config/auto-origination", 
        icon: IoFlash, 
      }, 
      { 
        id: "underwriting", 
        label: "Underwriting", 
        path: "/dashboard/config/underwriting", 
        icon: IoCheckmarkCircle, 
      }, 
      { 
        id: "general", 
        label: "General", 
        path: "/dashboard/config/general", 
        icon: IoOptions, 
      }, 
      { 
        id: "quick-links", 
        label: "Quick Links", 
        path: "/dashboard/config/quick-links", 
        icon: IoLinkSharp, 
      }, 
    ], 
  }, 
  
  { 
    id: "reporting", 
    label: "Reporting", 
    icon: IoDocumentText, 
    iconOutline: IoDocumentTextOutline, 
    path: "/dashboard/reporting/overview", 
  }, 
  { 
    id: "quick-link", 
    label: "Quick Link", 
    icon: IoLink, 
    iconOutline: IoLinkOutline, 
    path: "/dashboard/quick-link/main", 
  }, 
];  